image: registry-gitlab.int.nfware.com/docker/images/ubuntu-nfware:22.04-dyn

variables:
  APTLY_PREFIX: nfware
  APTLY_DISTR: jammy-6.1
  APTLY_COMPONENT: main

stages:
  - build
  - publish

build_job:
  stage: build
  script:
    - rm -f ../*.deb ../*.ddeb
    - apt-get update
    - dch -v "`dpkg-parsechangelog -S Version | sed 's/-0//g'`-${CI_PIPELINE_ID}" -D unstable "Gitlab CI build"
    - mk-build-deps -i -r -t "apt-get --no-install-recommends -y" debian/control
    - dpkg-buildpackage -b -uc -us
    - mkdir packages
    - mv ../*.deb ../*.ddeb packages
  artifacts:
    paths:
      - packages
    expire_in: 30 min

publish_job:
    stage: publish
    only:
      - /^develop/
      - /^publish/
    script:
      - rm -rf ../aptly
      - git clone https://${CI_REGISTRY_USER}:${CI_JOB_TOKEN}@gitlab.int.nfware.com/devops/aptly ../aptly
      - ../aptly/publish-deb packages/*.deb packages/*.ddeb
